# Generated by Django 5.2.17 on 2026-08-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docas', '0001_initial'),
        ('transportadoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista_nome', models.CharField(max_length=200)),
                ('motorista_cpf', models.CharField(blank=True, max_length=14)),
                ('placa', models.CharField(max_length=8)),
                ('carga', models.CharField(blank=True, max_length=100)),
                ('tipo_operacao', models.CharField(choices=[('recebimento', 'Recebimento'), ('carregamento', 'Carregamento'), ('transferencia', 'Transferência')], max_length=20)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('patio', 'No pátio'), ('em_operacao', 'Em operação'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aguardando', max_length=20)),
                ('peso_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_saida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entrada_em', models.DateTimeField(blank=True, null=True)),
                ('saida_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('doca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='docas.doca')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='transportadoras.transportadora')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ('-criado_em',),
            },
        ),
    ]
