# Generated by Django 5.2.17 on 2026-08-26 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_motorista_veiculo_alter_movimentacao_motorista_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('entrada', 'Entrada registrada'), ('saida', 'Saída registrada'), ('atualizacao', 'Atualização')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='operacao.movimentacao')),
            ],
            options={
                'verbose_name': 'Histórico da movimentação',
                'verbose_name_plural': 'Histórico das movimentações',
                'ordering': ('-criado_em',),
            },
        ),
    ]
