# Generated by Django 5.2.17 on 2026-08-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('recebimento', 'Recebimento'), ('carregamento', 'Carregamento'), ('separacao', 'Em Separação'), ('aguardando', 'Aguardando'), ('atrasada', 'Atrasada'), ('bloqueada', 'Bloqueada'), ('manual', 'Manual')], default='livre', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
