# Generated by Django 5.2.17 on 2026-08-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacao', '0003_historicomovimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacaoWMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('sucesso', 'Sucesso'), ('erro', 'Erro'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('dados_wms', models.JSONField()),
                ('dados_mapeados', models.JSONField(blank=True, null=True)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('operador_wms', models.CharField(blank=True, max_length=100)),
                ('localizacao_wms', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sincronizacoes_wms', to='operacao.movimentacao')),
            ],
            options={
                'verbose_name': 'Sincronização WMS',
                'verbose_name_plural': 'Sincronizações WMS',
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['shipment_id', '-criado_em'], name='integracao__shipmen_e13297_idx'), models.Index(fields=['status', '-criado_em'], name='integracao__status_1d1887_idx')],
            },
        ),
    ]
